name: first-workflow
on: workflow_dispatch
jobs:
  firstjob:
    run-on: ubuntu-latest
    steps:
    - name: print greeting
      run: echo "Hello world"
    - name: print goodbye
      run: echo "Good-bye"
